### ISSUE TITLE
?!

### ISSUE THREAD

**Issue by rjm-codes** [zBlakee/remindo#1]
didn't u have another one of these or am I high lol

**Comment by rjm-codes** [comment]
it was like

**Comment by rjm-codes** [comment]
zBlakee/todo or something

**Comment by rjm-codes** [comment]
now we have zBlakee/remindo repo

**Comment by rjm-codes** [comment]
maybe just a rename

**Comment by rjm-codes** [comment]
ok confirmed I found [it](https://github.com/zBlakee/TODO)

**Comment by rjm-codes** [comment]
@zBlakee hi

**Comment by Nevvulo** [comment]
what do you want
yes i had a repo named TODO, it doesn't do the same thing as this
